### PR TITLE
Add include path for LV2

### PR DESCRIPTION
**Pull request by runiq**
I'm trying to [package Ratatouille for Flatpak](https://github.com/runiq/org.freedesktop.LinuxAudio.Plugins.Ratatouille) and this was the first hurdle.

### CODE REVIEW

**Comment by brummer10** [comment]
Usually pgk-config lv2 comes out empty and the lv2 header been found in the system include path. If it does something for a flatpack build, I think it is better to keep it as a patch there.

**Comment by runiq** [comment]
That's fair, I can do that. But... why do that only for the LV2 headers? Libsndfile, Cairo, etc. appear to bell handled by pkg-config as well.

**Comment by brummer10** [comment]
lv2 isn't a library, it's "just" a set of header files, so it doesn't comes with a lv2.pc file. cairo and sndfile does that and implement this way there own dependencies. For example cairo gives:
 ```
pkg-config --cflags --libs cairo
-I/usr/include/cairo -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/pixman-1 -lcairo
```
while 
`pkg-config --cflags --libs lv2 `
return empty with regular lv2 instalation. So, when adding lv2 to the pkg-config flags helps on flatpack, flatpack would properly added a pc file for lv2. 
The usual way to use the lv2 headers is to just include them via the include path of the host system, no linking is needed, hence no ldfalgs to add.

**Comment by runiq** [comment]
I'll have to noodle on this a bit, but it makes sense. Thanks for the explanation, and for your patience. :)

**Pull request closed without merging**
